### ISSUE TITLE
Publish to crates.io?

### ISSUE THREAD

**Issue by borsboom** [Phrohdoh/ynab-rs#16]
Do you have any plans to publish this to crates.io?  It looks like there is already a different `ynab-api` there, but it's auto-generated from the Swagger spec.

At the moment I'm torn between forking the auto-generated version, which doesn't handle YNAB API error responses and has some other problems, or adding more API endpoints to this library (which appears to have a fairly complete set of types already).

**Comment by phrohdoh** [comment]
Hello!

There are plans to publish the libs and a bin to [crates.io], but I don't see that
happening for quite some time since this project is still very much alpha
software and only implements a tiny portion of the current API.

On top of that the test coverage is pretty poor.  I began this project before
learning [TDD] and would like to go back and rewrite this with TDD.

Some of the fields that are currently non-`Option`al need to be `Option`al but
I was discovering this in a one-off fashion when [serde] panics regarding a
missing field.

One of my goals with this repo is to publish multiple crates.
One for just the domain models, one for the API models (not sure if
splitting these two really makes sense, we'll see), one that is a typed HTTP
client, and another that is actually a binary CLI with plumbing and porcelain
commands (with porcelain probably built on top of the plumbing, similar to
`git` being comprised of shell commands, etc).

All of that to say there is still lots of work to be done on this project before
I'd want to publish it and it _appears_ to me that your [cli-for-ynab] project
is further along.

Given my rambling, what could this project do to best serve you and others
that may want to build YNAB tools in Rust (and Rust-friendly langs)?

[crates.io]: https://crates.io
[TDD]: https://en.wikipedia.org/wiki/Test-driven_development
[cli-for-ynab]: https://github.com/borsboom/cli-for-ynab

**Comment by phrohdoh** [comment]
Oh also another thing to keep in mind is that if/when I rewrite this project in
TDD fashion I'll probably also change the license to GPLv3 or AGPLv3 (currently
it is MIT).

I understand this may not work best for whatever end you and others may have in
mind but I am hopeful that a change like that would help people collectively.

**Comment by borsboom** [comment]
I used auto-generated Rust code from the Swagger spec for `cli-for-ynab`, which I then modified quite a bit.  At this point, though, that code is incompatible with current versions of Rust and its libraries, and updating it all doesn't seem worth it considering that I wasn't all that happy with the auto-generated code anyway.  That's why I'm looking at what's out there now.  The Rust OpenAPI generator has improved a fair bit since then, and the new auto-generated code in the `ynab-api` crate on crates.io looks like a decent starting point.

It sounds like this project is in flux and you need some time to work on overall design before it makes sense for someone else to start adding stuff to it, so I think I'll go with forking the new auto-generated code for now.

Thanks for answering!
